version: "3.7"

volumes:
  octo_db:

services:
  octo-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: Obron1587
    volumes:
      - octo_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@octo.ai
      PGADMIN_DEFAULT_PASSWORD: Obron1587
    ports:
      - "80:80"
