networks:
  - lan: 10.0.0.
    pwd: SecretPass
    range:
      - 2
      - 254
    usr: my_username
db_connection:
  dbms: postgresql
  usr: postgres
  pwd: DBPwd
  host: localhost
  port: 5432
  db: postgres
